<a href="https://colab.research.google.com/github/ghiyaa/proj261/blob/main/Decision_Tree_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np

import sklearn 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeClassifier

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [4]:
# please provide the path where HIGGS_train.csv is located

df = pd.read_csv('/content/gdrive/My Drive/proj261/HIGGS_train.csv', low_memory = False, header = None)

In [5]:
import sys
# here provide the path where preprocessing_module is located
sys.path.append('/content/gdrive/MyDrive/proj261/')

from preprocessing_module import Preprocessing
# Cleaning the data
X, y = Preprocessing(df)
print(X, y)

[260692]
0           1.0
1          1.75
2         0.442
3           1.5
4         0.708
5         -1.28
6          1.13
7         0.902
8     -1.92E-01
9          2.17
10        0.562
11        0.219
12        0.864
13          0.0
14        0.492
15        0.317
16       -0.221
17          NaN
18        0.508
19         1.45
20         1.58
21     0.00E+00
22        0.718
23         1.02
24        0.989
25        0.732
26        0.266
27        0.891
28        0.758
Name: 260692, dtype: object
"1.01" 261026 8
[261025]
error 490959 21
[261025, 490958]
s 490960 21
[261025, 490958, 490959]
[[0.869 -0.635 0.226 ... 0.722 0.989 0.877]
 [0.908 0.329 0.359 ... 0.78 0.992 0.798]
 [0.799 1.47 -1.64 ... 0.803 0.866 0.78]
 ...
 [1.07 0.364 0.344 ... 0.852 0.908 0.789]
 [1.18 -0.173 -1.46 ... 0.745 0.741 0.728]
 [0.771 -0.133 -1.02 ... 0.51 1.04 0.905]] [1. 1. 1. ... 1. 1. 0.]


In [8]:
# Split the data into training 97.5% and test 2.5% sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.025, random_state = 42)

# Print the shape of the training and test sets
print("Training set shape:", X_train.shape, y_train.shape)
print("Test set shape:", X_test.shape, y_test.shape)

Training set shape: (584996, 28) (584996,)
Test set shape: (15000, 28) (15000,)


In [9]:
# Feature scaling: Standard Normalization

# Create a StandardScaler object
scaler = StandardScaler()

# Fit the scaler on the training data and transform it
X_train = scaler.fit_transform(X_train)
# Transform the test data using the parameters learned from the training data
X_test = scaler.transform(X_test)

In [10]:
# Model 1:

# Build a decision tree model
dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 55)

# Train the model on the training data
dt.fit(X_train, y_train)

# Predict classes of the test data
y_pred_train = dt.predict(X_train)
y_pred_test = dt.predict(X_test)

# Calculate the test accuracy
accuracy_train = sklearn.metrics.accuracy_score(y_train, y_pred_train)
accuracy_test = sklearn.metrics.accuracy_score(y_test, y_pred_test)

print('Accuracy on train:', accuracy_train)
print('Accuracy on test:', accuracy_test)

Accuracy on train: 1.0
Accuracy on test: 0.6458


In [11]:
# Model 2: (with max_depth = 10)

# Build a decision tree model
dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 55, max_depth = 10)

# Train the model on the training data
dt.fit(X_train, y_train)

# Predict classes of the test data
y_pred_train = dt.predict(X_train)
y_pred_test = dt.predict(X_test)

# Calculate the test accuracy
accuracy_train = sklearn.metrics.accuracy_score(y_train, y_pred_train)
accuracy_test = sklearn.metrics.accuracy_score(y_test, y_pred_test)

print('Accuracy on train:', accuracy_train)
print('Accuracy on test:', accuracy_test)

Accuracy on train: 0.710013401801038
Accuracy on test: 0.7058
